# CMake generated Testfile for 
# Source directory: /root/temp/cmake-3.17.2/Tests/CMakeLib
# Build directory: /root/temp/cmake-3.17.2/Tests/CMakeLib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMakeLib.testArgumentParser "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testArgumentParser")
set_tests_properties(CMakeLib.testArgumentParser PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestBinPacker "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testCTestBinPacker")
set_tests_properties(CMakeLib.testCTestBinPacker PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceAllocator "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testCTestResourceAllocator")
set_tests_properties(CMakeLib.testCTestResourceAllocator PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceSpec "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testCTestResourceSpec" "/root/temp/cmake-3.17.2/Tests/CMakeLib")
set_tests_properties(CMakeLib.testCTestResourceSpec PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceGroups "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testCTestResourceGroups")
set_tests_properties(CMakeLib.testCTestResourceGroups PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testGccDepfileReader "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testGccDepfileReader" "/root/temp/cmake-3.17.2/Tests/CMakeLib")
set_tests_properties(CMakeLib.testGccDepfileReader PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testGeneratedFileStream "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testGeneratedFileStream")
set_tests_properties(CMakeLib.testGeneratedFileStream PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testRST "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testRST" "/root/temp/cmake-3.17.2/Tests/CMakeLib")
set_tests_properties(CMakeLib.testRST PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testRange "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testRange")
set_tests_properties(CMakeLib.testRange PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testOptional "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testOptional")
set_tests_properties(CMakeLib.testOptional PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testString "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testString")
set_tests_properties(CMakeLib.testString PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testStringAlgorithms "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testStringAlgorithms")
set_tests_properties(CMakeLib.testStringAlgorithms PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testSystemTools "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testSystemTools")
set_tests_properties(CMakeLib.testSystemTools PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUTF8 "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testUTF8")
set_tests_properties(CMakeLib.testUTF8 PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testXMLParser "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testXMLParser")
set_tests_properties(CMakeLib.testXMLParser PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testXMLSafe "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testXMLSafe")
set_tests_properties(CMakeLib.testXMLSafe PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testFindPackageCommand "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testFindPackageCommand")
set_tests_properties(CMakeLib.testFindPackageCommand PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVProcessChain "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testUVProcessChain" "/root/temp/cmake-3.17.2/Tests/CMakeLib/testUVProcessChainHelper")
set_tests_properties(CMakeLib.testUVProcessChain PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVRAII "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testUVRAII")
set_tests_properties(CMakeLib.testUVRAII PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVStreambuf "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testUVStreambuf" "/root/temp/cmake-3.17.2/bin/cmake")
set_tests_properties(CMakeLib.testUVStreambuf PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCMExtMemory "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testCMExtMemory")
set_tests_properties(CMakeLib.testCMExtMemory PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCMExtAlgorithm "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLibTests" "testCMExtAlgorithm")
set_tests_properties(CMakeLib.testCMExtAlgorithm PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;64;add_test;/root/temp/cmake-3.17.2/Tests/CMakeLib/CMakeLists.txt;0;")
subdirs("PseudoMemcheck")
