# CMake generated Testfile for 
# Source directory: /root/temp/cmake-3.17.2/Tests/CMakeTests
# Build directory: /root/temp/cmake-3.17.2/Tests/CMakeTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMake.List "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/ListTest.cmake")
set_tests_properties(CMake.List PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;13;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.VariableWatch "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/VariableWatchTest.cmake")
set_tests_properties(CMake.VariableWatch PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;14;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.Include "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/IncludeTest.cmake")
set_tests_properties(CMake.Include PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;15;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.FindBase "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/FindBaseTest.cmake")
set_tests_properties(CMake.FindBase PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;16;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.Toolchain "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/ToolchainTest.cmake")
set_tests_properties(CMake.Toolchain PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;17;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.GetFilenameComponentRealpath "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
set_tests_properties(CMake.GetFilenameComponentRealpath PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;18;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.Version "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/VersionTest.cmake")
set_tests_properties(CMake.Version PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;19;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.Message "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/MessageTest.cmake")
set_tests_properties(CMake.Message PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;20;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.File "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/FileTest.cmake")
set_tests_properties(CMake.File PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;21;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.ImplicitLinkInfo "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
set_tests_properties(CMake.ImplicitLinkInfo PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;22;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.ModuleNotices "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/ModuleNoticesTest.cmake")
set_tests_properties(CMake.ModuleNotices PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;23;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.GetProperty "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/GetPropertyTest.cmake")
set_tests_properties(CMake.GetProperty PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;24;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.If "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/IfTest.cmake")
set_tests_properties(CMake.If PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;25;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.String "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/StringTest.cmake")
set_tests_properties(CMake.String PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;26;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.Math "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/MathTest.cmake")
set_tests_properties(CMake.Math PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;27;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.CMakeMinimumRequired "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
set_tests_properties(CMake.CMakeMinimumRequired PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;28;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.CompilerIdVendor "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/CompilerIdVendorTest.cmake")
set_tests_properties(CMake.CompilerIdVendor PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;29;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.ProcessorCount "/root/temp/cmake-3.17.2/bin/cmake" "-DKWSYS_TEST_EXE=/root/temp/cmake-3.17.2/Source/kwsys/cmsysTestsCxx" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/ProcessorCountTest.cmake")
set_tests_properties(CMake.ProcessorCount PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;30;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.PushCheckState "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/PushCheckStateTest.cmake")
set_tests_properties(CMake.PushCheckState PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;31;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.While "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/WhileTest.cmake")
set_tests_properties(CMake.While PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;32;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.CMakeHostSystemInformation "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeHostSystemInformationTest.cmake")
set_tests_properties(CMake.CMakeHostSystemInformation PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;33;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.FileDownload "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/FileDownloadTest.cmake")
set_tests_properties(CMake.FileDownload PROPERTIES  FAIL_REGULAR_EXPRESSION "Unexpected status" PASS_REGULAR_EXPRESSION "file already exists with expected MD5 sum" _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;35;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.FileDownloadBadHash "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/FileDownloadBadHashTest.cmake")
set_tests_properties(CMake.FileDownloadBadHash PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;40;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.FileUpload "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/FileUploadTest.cmake")
set_tests_properties(CMake.FileUpload PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;45;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.ELF "/root/temp/cmake-3.17.2/bin/cmake" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/ELFTest.cmake")
set_tests_properties(CMake.ELF PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;48;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.EndStuff "/root/temp/cmake-3.17.2/bin/cmake" "-Ddir:STRING=/root/temp/cmake-3.17.2/Tests/CMakeTests/EndStuffTest" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/EndStuffTest.cmake")
set_tests_properties(CMake.EndStuff PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;54;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.GetPrerequisites "/root/temp/cmake-3.17.2/bin/cmake" "-DConfiguration:STRING=Release" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/GetPrerequisitesTest.cmake")
set_tests_properties(CMake.GetPrerequisites PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;56;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.PolicyCheck "/root/temp/cmake-3.17.2/bin/cmake" "-DCMake_BINARY_DIR:PATH=/root/temp/cmake-3.17.2" "-DCMake_SOURCE_DIR:PATH=/root/temp/cmake-3.17.2" "-DGIT_EXECUTABLE:STRING=/usr/bin/git" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/PolicyCheckTest.cmake")
set_tests_properties(CMake.PolicyCheck PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;64;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.CheckSourceTree "/root/temp/cmake-3.17.2/bin/cmake" "-DCMake_BINARY_DIR:PATH=/root/temp/cmake-3.17.2" "-DCMake_SOURCE_DIR:PATH=/root/temp/cmake-3.17.2" "-DGIT_EXECUTABLE:STRING=/usr/bin/git" "-DHOME:STRING=/root" "-P" "/root/temp/cmake-3.17.2/Tests/CMakeTests/CheckSourceTreeTest.cmake")
set_tests_properties(CMake.CheckSourceTree PROPERTIES  _BACKTRACE_TRIPLES "/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;7;add_test;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;79;AddCMakeTest;/root/temp/cmake-3.17.2/Tests/CMakeTests/CMakeLists.txt;0;")
